version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/gradle-swagger-generator-plugin
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  gh-pages:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/gradle-swagger-generator-plugin
    steps:
      - run: |
          mkdir -p $HOME/bin
          curl -L -o $HOME/bin/ghcp https://github.com/int128/ghcp/releases/download/v1.3.0/ghcp_linux_amd64
          chmod +x $HOME/bin/ghcp
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: ./gradlew acceptance-test:example-docs
      - run: |
          ghcp -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" -b gh-pages \
            -m "Published by $CIRCLE_BUILD_URL" \
            -C acceptance-test/build \
            examples

  release:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/gradle-swagger-generator-plugin
    steps:
      - run: |
          mkdir -p $HOME/bin
          curl -L -o $HOME/bin/ghcp https://github.com/int128/ghcp/releases/download/v1.3.0/ghcp_linux_amd64
          chmod +x $HOME/bin/ghcp
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          mkdir -p $HOME/.gradle
          echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> $HOME/.gradle/gradle.properties
          echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> $HOME/.gradle/gradle.properties
      - run: ./gradlew publishPlugins
      - run: |
          sed -i -e "s/version '[0-9.]*'/version '$CIRCLE_TAG'/g" README.md template-project/build.gradle
      - run: |
          ghcp -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" -B "verify-$CIRCLE_TAG" \
            -m "Release $CIRCLE_TAG" \
            README.md template-project/build.gradle

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
            tags:
              only: /.*/
      - gh-pages:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - fix-gh-pages
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
